import {randomInt,randomBytes} from 'node:crypto';
import {MAX_PLAYERS,MIN_PLAYERS,WORDS,Phase,Role,PublicRoom,PersonalState,PublicResult,Clue} from '@hidden-impostor/shared';
export type Player={id:string;name:string;score:number;connected:boolean;socketId?:string;reconnectToken:string;role:Role|null;hasVoted:boolean;disconnectedAt:number|null};
export type Room={code:string;hostPlayerId:string;players:Map<string,Player>;phase:Phase;roundNumber:number;secretWord:string|null;impostorId:string|null;clues:Clue[];votes:Map<string,string>;currentPlayerId:string|null;phaseEndsAt:number|null;result:PublicResult|null;createdAt:number};
export const makeCode=()=>randomBytes(4).toString('hex').slice(0,6).toUpperCase();
export const makeId=()=>randomBytes(12).toString('hex');
export const makeToken=()=>randomBytes(24).toString('hex');
export function createRoom(name:string){const p:Player={id:makeId(),name,score:0,connected:true,reconnectToken:makeToken(),role:null,hasVoted:false,disconnectedAt:null};return {room:{code:makeCode(),hostPlayerId:p.id,players:new Map([[p.id,p]]),phase:'LOBBY',roundNumber:0,secretWord:null,impostorId:null,clues:[],votes:new Map(),currentPlayerId:null,phaseEndsAt:null,result:null,createdAt:Date.now()} as Room,player:p};}
const active=(r:Room)=>[...r.players.values()].filter(p=>p.connected);
export function publicState(r:Room):PublicRoom{return {code:r.code,hostPlayerId:r.hostPlayerId,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:p.score,connected:p.connected,isHost:p.id===r.hostPlayerId})),phase:r.phase,roundNumber:r.roundNumber,clues:[...r.clues],currentPlayerId:r.currentPlayerId,phaseEndsAt:r.phaseEndsAt,result:r.result};}
export function personalState(r:Room,p:Player):PersonalState{return {...publicState(r),self:{id:p.id,name:p.name,role:p.role,secretWord:p.role==='CREW'?r.secretWord:null,hasVoted:p.hasVoted}};}
export function startRound(r:Room,now=Date.now()){const ps=active(r);if(ps.length<MIN_PLAYERS||ps.length>MAX_PLAYERS||r.phase!=='LOBBY')throw Error('Cannot start round');r.roundNumber++;r.secretWord=WORDS[randomInt(WORDS.length)];r.impostorId=ps[randomInt(ps.length)].id;r.clues=[];r.votes.clear();ps.forEach(p=>{p.role=p.id===r.impostorId?'IMPOSTOR':'CREW';p.hasVoted=false});r.phase='ROLE_REVEAL';r.currentPlayerId=null;r.phaseEndsAt=now+8000;r.result=null;}
export function beginClues(r:Room,now=Date.now()){if(r.phase!=='ROLE_REVEAL')throw Error('Invalid phase');const ps=active(r);r.phase='CLUE_GIVING';r.currentPlayerId=ps[0]?.id??null;r.phaseEndsAt=now+120000;}
export function submitClue(r:Room,p:Player,text:string,now=Date.now()){if(r.phase!=='CLUE_GIVING'||r.currentPlayerId!==p.id)throw Error('Not your turn');if(text.trim().length<1||text.trim().length>120)throw Error('Invalid clue');r.clues.push({playerId:p.id,playerName:p.name,text:text.trim()});const ps=active(r),i=ps.findIndex(x=>x.id===p.id);r.currentPlayerId=ps[(i+1)%ps.length]?.id??null;r.phaseEndsAt=now+120000;if(r.clues.length>=ps.length){r.phase='DISCUSSION';r.currentPlayerId=null;r.phaseEndsAt=now+60000;}}
export function beginVoting(r:Room,now=Date.now()){if(r.phase!=='DISCUSSION')throw Error('Invalid phase');r.phase='VOTING';r.votes.clear();r.phaseEndsAt=now+45000;active(r).forEach(p=>p.hasVoted=false);}
export function submitVote(r:Room,p:Player,target:string,now=Date.now()){if(r.phase!=='VOTING'||!p.connected||p.hasVoted)throw Error('Vote not allowed');if(!r.players.has(target)||!r.players.get(target)!.connected||target===p.id)throw Error('Invalid target');r.votes.set(p.id,target);p.hasVoted=true;if(r.votes.size>=active(r).length)finish(r,now);}
export function finish(r:Room,now=Date.now()){if(r.phase!=='VOTING')return;const counts=new Map<string,number>();for(const t of r.votes.values())counts.set(t,(counts.get(t)??0)+1);const max=Math.max(0,...counts.values());const leaders=[...counts.entries()].filter(([,n])=>n===max);const caught=leaders.length===1&&leaders[0][0]===r.impostorId;const imp=r.players.get(r.impostorId!);const most=leaders.length===1?r.players.get(leaders[0][0])?.name??null:null;r.result={crewWon:caught,impostorName:imp?.name??'Unknown',mostVotedName:most,votes:max};for(const p of r.players.values()){if(p.role==='CREW'&&caught)p.score+=2;if(p.role==='IMPOSTOR'&&!caught)p.score+=3;}r.phase='RESULT';r.currentPlayerId=null;r.phaseEndsAt=now+15000;}
export function playAgain(r:Room,now=Date.now()){if(r.phase!=='RESULT')throw Error('Invalid phase');r.phase='LOBBY';r.secretWord=null;r.impostorId=null;r.clues=[];r.votes.clear();r.result=null;r.currentPlayerId=null;r.phaseEndsAt=null;r.players.forEach(p=>{p.role=null;p.hasVoted=false});}
export function removeExpired(r:Room,now=Date.now()){for(const [id,p] of r.players)if(!p.connected&&p.disconnectedAt&&now-p.disconnectedAt>5*60_000)r.players.delete(id);if(!r.players.has(r.hostPlayerId)){const n=[...r.players.values()][0];if(n)r.hostPlayerId=n.id;}return r.players.size===0;}
